version: '3'

services:

  ubuntu:

    container_name: ubuntu

    build: ./ubuntu

    environment:
     # - TZ='Asia/Tokyo'
      - DISPLAY=:1 
    
    volumes:
      - ./vnc_server:/usr/src/vnc_server

    ports:
      - 5900:5900
    
    working_dir: /usr/src/vnc_server

    command: Xvfb :1 -screen 0 1280x720x16

