FROM ubuntu:20.04

RUN apt-get update && apt-get install -y tzdata

ENV TZ=Asia/Tokyo

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential libvncserver-dev libx11-dev libxtst-dev  xvfb x11-apps xterm x11vnc firefox
    

